### ISSUE TITLE
[FEATURE] Refactoring Component Cookienotice.vue

### ISSUE THREAD

**Issue by dm-heinze** [hubblecommerce/hubble-frontend-pwa#10]
**Is your feature request related to a problem? Please describe.**
As declared in the hubble coding guidelines, a Vue component should display context via v-text and be selfclosing. Therefore to standardize the Cookienotice component the template need to change.

**Describe the solution you'd like**
Add selfclosing tag to template parts where necessary.

**Comment by Zermoran** [comment]
**Is your feature request related to a problem? Please describe.**
As declared in the hubble coding guidelines, a Vue component should display context via v-text and be selfclosing, should display static text only through locales and should handle media queries in scss whenever possible. Cause media queries are handled with v-if statements the template has 2 almost identical parts which are redundant.

**Describe the solution you'd like**
Add selfclosing tag to template parts, change static text to be translatable, change media queries to be handled by scss and remove redundacy in template.
