### ISSUE TITLE
[FEATURE] Sticky Toolbar (Product-Filter) Jump

### ISSUE THREAD

**Issue by Gar-nele** [hubblecommerce/hubble-frontend-pwa#114]
**Is your feature request related to a problem? Please describe.**
Product-listing-toolbar jumps up when scrolled down. Select-Box-Border can be seen through fixed toolbar. 

**Describe the solution you'd like**
Adjusted toolbar-z-index and the values which are used to set sticky-flag for fixed toolbar.

**Comment by dm-heinze** [comment]
Fixed with Version 1.5.0
