### ISSUE TITLE
[FEATURE] implementation of jest unit testing in hubble

### ISSUE THREAD

**Issue by Zermoran** [hubblecommerce/hubble-frontend-pwa#116]
**Is your feature request related to a problem? Please describe.**
Reasons for Jest testing in hubble:

- Refactoring a component can break it in unexpected ways, unit tests could help prevent unexpected consequences
- Changes in API can be detected by jest tests early and can be addressed quickly

**Describe the solution you'd like**
Implement Jest unit testing to ensure functionality of complex components and modules after refactoring or changes in external API

**Comment by dm-heinze** [comment]
Closed because deprecated in 2.0.0
