### ISSUE TITLE
[BUG] Multiple product-pictures caused by screen resizing

### ISSUE THREAD

**Issue by Gar-nele** [hubblecommerce/hubble-frontend-pwa#56]
**Describe the bug**
Decreasing and increasing browser window/screensize cause display of multiple product-pictures.

**Versions**
hubble: 1.1.7
nuxt: 2.14.6
node: 10.20.0

**Steps to Reproduce**
1. Go to Product-Details (Click on any product)
2. Decrease browser window or change screensize via device tool to e.g. tablet-size (at least  width: 1023px). 
3. Increase screensize back to desktop-size.
4. See error in the form of two product-pictures.

**Expected behavior**
No change of the amount of pictures shown.

**Current behavior**
Each repetition of changing the screensize creates another product-picture.

**Comment by dm-heinze** [comment]
Closed by issue#9 Theme 2.0
