### ISSUE TITLE
[BUG] Search not functioning

### ISSUE THREAD

**Issue by Gar-nele** [hubblecommerce/hubble-frontend-pwa#57]
**Describe the bug**
Search without any result and failing API request.

**API Type**
sw

**Versions**
hubble: 1.1.7
nuxt: 2.14.6
node: 10.20.0

**Steps to Reproduce**
1. Click on Search input field
2. type in any product title
3. See not result after search
4. press enter
5. see error 

**Expected behavior**
Searching, finding and listing products.

**Current behavior**
Finding no results and causing API request fail.

**Comment by dm-heinze** [comment]
Used Shopwares new store api endpoints for fixing the search. 

Todo:
Check if all filters are still valid

**Comment by dm-heinze** [comment]
Fixed in Version 1.5.0
