### ISSUE TITLE
[FEATURE] Refactoring summary.vue and related files

### ISSUE THREAD

**Issue by Gar-nele** [hubblecommerce/hubble-frontend-pwa#92]
**Is your feature request related to a problem? Please describe.**
As declared in the hubble coding guidelines, a component should display content via v-text.

Furthermore summary conainer is not displayed properly in mobile view.

**Describe the solution you'd like**
Added v-text.
Fixed container-display in mobile-view.

**Comment by dm-heinze** [comment]
Checkout refactoring is part of #9
